### ISSUE TITLE
Update the "Try it Now" section, add "oc cluster up"

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift.org#47]
See https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md.

The `oc cluster up` command was added in OpenShift 3.3.
Related blog post: https://blog.openshift.com/whats-new-openshift-3-3-developer-experience/

Related (but different) issue: #18

**Comment by rhcarvalho** [comment]
FYI @jiri-fiala @jsvgoncalves

**Comment by jsvgoncalves** [comment]
#46
