### ISSUE TITLE
Page is redirecting

### ISSUE THREAD

**Issue by thesteve0** [openshift/openshift.org#62]
Hey folks:
So there is an old page in the repo for all in one 1.4 but when I go to 
https://www.openshift.org/vm/instructions1_4.html

it redirects to the VM page again which defeats the purpose of pointing people to the old instructions

https://github.com/openshift/openshift.org/blob/master/source/vm/index.html.erb#L84

Can we please fix this ASAP @jsvgoncalves @wgordon17

**Comment by jiri-fiala** [comment]
This seems to be left behind in the commit from when we have not yet clarified the all in one stays, and the Minishift is to complement. Will be fixed soon (also redirecting all in one 1.2 and 1.3 instructions to 1.4).
