### ISSUE TITLE
Create a downloads page for the OC tools, other Origin assets

### ISSUE THREAD

**Issue by luciddreamz** [openshift/openshift.org#66]
We need a downloads page on openshift.org so that people can find the oc tools when they search "download oc tools" or related search terms. I would suggest either creating a YAML/AJAX based system (like we have for blogs, press releases on openshift.com) or something similar.

Example (doesn't have to look like this): https://www.vagrantup.com/downloads.html

Historical versions? https://releases.hashicorp.com/vagrant/

Also semi-interesting example:

- https://desktop.github.com/
- https://desktop.github.com/release-notes/mac/

Useful gist: https://gist.github.com/ncdc/985c3108e0457dd294f4963f14e80ea6

**Comment by wgordon17** [comment]
@luciddreamz Please review the staging page: https://staging-wgordon.rhcloud.com/download.html

The only link to /download.html is from the index page, the "oc" from "oc cluster up" is a link.

Thoughts?
