### ISSUE TITLE
Need short description for the repo

### ISSUE THREAD

**Issue by brgnepal** [openshift/openshift.org#82]
The repo lacks the description as pointed out below:

![screenshot from 2017-11-09 11-09-39](https://user-images.githubusercontent.com/1132451/32590117-a4b006c6-c53e-11e7-9313-5c34bdcc7691.png)

Description could be `Repo powering https://www.openshift.org/` or any else.

**Comment by brgnepal** [comment]
Any update here? It is an easy fix right?

**Comment by jiri-fiala** [comment]
The repo description has been added.
